# Generated by Django 4.2.11 on 2024-03-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Covid19LastCases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=200)),
                ("totalCases", models.CharField(max_length=50)),
                ("newCases", models.CharField(max_length=50)),
                ("totalDeaths", models.CharField(max_length=50)),
                ("newDeaths", models.CharField(max_length=50)),
                ("totalRecovered", models.CharField(max_length=50)),
                ("newRecovered", models.CharField(max_length=50)),
                ("activeCases", models.CharField(max_length=50)),
                ("seriousCritical", models.CharField(max_length=50)),
                ("population", models.CharField(max_length=100)),
                ("continent", models.CharField(max_length=90)),
                ("date_saved", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
