# Generated by Django 4.2.11 on 2024-03-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corona_virus_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestJust",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=255)),
            ],
        ),
    ]
